# Generated by Django 3.2.7 on 2021-09-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='vendor/')),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
