# Generated by Django 3.2.7 on 2021-09-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=22),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amt', models.FloatField()),
                ('sale', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=400)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.product')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
