# Generated by Django 3.2.7 on 2021-09-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_auto_20210928_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.sale'),
        ),
    ]
