# Generated by Django 3.2.7 on 2021-09-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_auto_20210928_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale',
            new_name='sale_date',
        ),
    ]
