# Generated by Django 3.2.7 on 2021-09-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_alter_sale_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
    ]
