# Generated by Django 3.2.7 on 2021-09-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0014_sale_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7.Customers'},
        ),
    ]
